### PR TITLE
Redesign the logo using a CPU instead of a gear

### PR DESCRIPTION
**Pull request by leouieda**
The gear logo was a bit too close to the Google Earth Engine logo. The
CPU version is still very much related and has more to do with
computers actually. Plus, we can play with "silicon" related puns
between CPUs and geoscience.

examples-for-readme

### CODE REVIEW

**Comment by leouieda** [comment]
@santisoler what do you think?

**Comment by leouieda** [comment]
For reference, this is the Google Earth Engine logo:

**Comment by santisoler** [comment]
I agree that the resemblance with the Google Earth Engine is disturbing haha.
And computers haven't work based on gears in a long time ([really?](https://www.youtube.com/watch?v=rdT1YT9AOPA)), and I doubt anyone could run our codes haha.

So I like the silicon replacement. I would make small changes. Instead of getting the colormap _inside_ the CPU, I think we can put it _on top_ (our thermal paste with diverging colormaps haha), like the Google Earth logo sits on top of the gear (maybe we could add a small shade too). And probably we can reduce the number of board tracks (are they board tracks or pins? :thinking:) to three per side, I think that would look better.

**Comment by leouieda** [comment]
> And computers haven't work based on gears in a long time (really?)

😮 

Thanks for the feedback. I'll make some alternatives to see what works.

**Comment by leouieda** [comment]
compgeolab-banner-top

---

compgeolab-banner-shadow

---

compgeolab-banner-3pins

--- 

3 pins really is better. I'm not sure about the shadow (I couldn't make it look nice without copying the shadow exactly, which I don't want to do). I kind of like the white gap a bit better in this case since it makes the colors pop a bit more.

What do you think?

**Comment by santisoler** [comment]
For the record, I'm fine with either one of the three. I kind of like the one with the shadow though, but maybe it needs a more "flat" design. I was thinking something like this:
compgeolab

**Comment by santisoler** [comment]
If we want to keep a more circular design, we could create a circle out of the colormap and center a small cpu on it. Like the one I made for the EGU slides: https://santisoler.github.io/talks/egu2020.html (slide 14), but with the colormap instead of the yellow background.

**Comment by leouieda** [comment]
I was hoping to avoid that type of shadow since it's kind of everywhere in the past 5 years or so. I'm actually warming up to the version without the shadow or the white space. I'm doing a few tweaks now.

I don't think we have to stick to the round theme if we're going for something different this time. I had already gotten used to the gear icon but for this it doesn't make much sense to go with round.

**Comment by santisoler** [comment]
> I was hoping to avoid that type of shadow since it's kind of everywhere in the past 5 years or so. I'm actually warming up to the version without the shadow or the white space. I'm doing a few tweaks now.
>
> I don't think we have to stick to the round theme if we're going for something different this time. I had already gotten used to the gear icon but for this it doesn't make much sense to go with round.

Sure Leo! I will agree with any choice you make. All designs look good, we are just discussing minor details.

**Comment by leouieda** [comment]
compgeolab-3pins

Now I remember why I added the gap between the colors and the gear 🙂  It doesn't work with a light version.

**Comment by leouieda** [comment]
Thanks for the input, as always @santisoler! After playing around with colors and backgrounds, this is what I thought looks nicer most of the time. So I'm going to go with this one. 

examples-for-readme

**Pull request merged**
